name: Build 2DMBIE

on:
  pull_request:
    branches: 
    - main
    - alpha

  workflow_dispatch:

jobs: 
  Godot:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: 2DMBIE
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.builds.outputs.build }}
